- django_project/frontend/migrations/0010_layer_simplification.py
fix error 'relation protected_areas_2022_small_scale does not exist' in test
> Fix migration table not exists

- django_project/frontend/utils/sanbi_styling_dark.json
- django_project/frontend/utils/sanbi_styling_light.json
Update new styles from @Jeremy-Prior
> Update styles v12: fix two critical biodiversity areas not showing

- django_project/species/views.py
This PR created to resolve issue comment [reference](https://github.com/kartoza/sawps/pull/646/#issuecomment-1633715087)
> Update query to get only Species data

- django_project/frontend/src/containers/MainPage/Map/MapUtility.ts
This is for #672. cc: @amyburness 
Preview:
> Change site type label to Protected Area in popup

- django_project/fixtures/context_layer.json
- django_project/frontend/src/containers/MainPage/Map/MapUtility.ts
> Change Critical Biodiversity Label

- django_project/frontend/api_views/metrics.py
- django_project/frontend/filters/metrics.py
- django_project/frontend/package-lock.json
- django_project/frontend/package.json
- django_project/frontend/serializers/metrics.py
- django_project/frontend/src/containers/MainPage/Metrics/ActivityDonutChart.tsx
- django_project/frontend/src/containers/MainPage/Metrics/index.scss
- django_project/frontend/src/containers/MainPage/Metrics/index.tsx
- django_project/frontend/static_mapping.py
- django_project/frontend/tests/test_home_view.py
- django_project/frontend/tests/test_map_view.py
- django_project/frontend/tests/test_metrics.py
- django_project/frontend/urls.py
- django_project/population_data/test_population_data_models.py
- django_project/species/factories.py
This PR is for #660 
Integration Donut Chart
Before : 
After:
> Activity data as % of total population

- django_project/frontend/src/containers/MainPage/Metrics/ActivityDonutChart.tsx
This PR is for #719
Before:
After:
> Fixes for donut chart

- django_project/frontend/api_views/metrics.py
- django_project/frontend/filters/metrics.py
- django_project/frontend/serializers/metrics.py
- django_project/frontend/src/containers/MainPage/Metrics/DensityBarChart.tsx
- django_project/frontend/src/containers/MainPage/Metrics/SpeciesLineChart.tsx
- django_project/frontend/src/containers/MainPage/Metrics/index.tsx
- django_project/frontend/tests/test_metrics.py
- django_project/frontend/urls.py
This PR is for #663 
Before : 
After
src="https://github.com/kartoza/sawps/assets/138113337/70c163d2-03ed-4553-9a26-1b5e2591925c">
> Species Population Totals and Density  

- django_project/frontend/api_views/metrics.py
- django_project/frontend/filters/metrics.py
- django_project/frontend/src/containers/MainPage/Metrics/PopulationCategoryChart.tsx
- django_project/frontend/src/containers/MainPage/Metrics/index.tsx
- django_project/frontend/tests/test_metrics.py
- django_project/frontend/urls.py
- django_project/frontend/utils/metrics.py
This Pr is for #664 
Before:
After:
> Number of properties per population category

- deployment/image-index.yml
This is for plumber deployment cc: @tharanathkartoza
> Update image index

- django_project/frontend/api_views/metrics.py
- django_project/frontend/filters/metrics.py
- django_project/frontend/serializers/metrics.py
- django_project/frontend/src/containers/MainPage/Metrics/ActivityDonutChart.tsx
- django_project/frontend/src/containers/MainPage/Metrics/DensityBarChart.tsx
- django_project/frontend/src/containers/MainPage/Metrics/PopulationCategoryChart.tsx
- django_project/frontend/src/containers/MainPage/Metrics/SpeciesLineChart.tsx
- django_project/frontend/src/containers/MainPage/Metrics/index.scss
- django_project/frontend/src/containers/MainPage/Metrics/index.tsx
- django_project/frontend/tests/test_metrics.py
- django_project/frontend/urls.py
This PR is for Update api speciesPopulationCount and integrate filters on metrics
Before : 
After:
> Update api speciesPopulationCount and integrate filters

- .gitignore
- deployment/docker/requirements.txt
- django_project/core/settings/contrib.py
> Add django-easy-audit, modify the settings

- django_project/frontend/api_views/population.py
This is to fix filtering in taxon dropdown for online form. Also fix sampling size unit serializer.
> fix filter in taxon dropdown and sampling size unit

- django_project/frontend/api_views/metrics.py
- django_project/frontend/src/containers/MainPage/Metrics/PropertyAvailable.tsx
- django_project/frontend/src/containers/MainPage/Metrics/index.tsx
- django_project/frontend/tests/test_metrics.py
- django_project/frontend/urls.py
- django_project/frontend/utils/metrics.py
- django_project/species/factories.py
This PR is for #765 
Before : 
After:
> Integration area available to species

- django_project/frontend/api_views/metrics.py
- django_project/frontend/src/containers/MainPage/Metrics/PropertyType.tsx
- django_project/frontend/src/containers/MainPage/Metrics/index.tsx
- django_project/frontend/tests/test_metrics.py
- django_project/frontend/urls.py
- django_project/frontend/utils/metrics.py
This PR is for #766
Before : 
After:
> integration property type chart

- django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
- django_project/frontend/src/containers/MainPage/SideBar/index.scss
- django_project/frontend/src/reducers/SpeciesFilter.ts
- django_project/frontend/tests/test_metrics.py
This PR is for #786 
Before : 
After :
> Integration editable year function

- django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
This PR is for #786 
Before:
After:
> Fixes for editable chart

- django_project/frontend/templates/notifications.html
> patch: capitalisation of notification #809

- django_project/frontend/api_views/metrics.py
- django_project/frontend/filters/metrics.py
- django_project/frontend/serializers/metrics.py
- django_project/frontend/src/containers/MainPage/Metrics/DensityBarChart.tsx
- django_project/frontend/src/containers/MainPage/Metrics/PropertyAvailable.tsx
- django_project/frontend/tests/test_metrics.py
- django_project/frontend/urls.py
- django_project/frontend/utils/metrics.py
This PR is for #762
Before:
After:
> Fix density chart

- django_project/frontend/api_views/metrics.py
- django_project/frontend/serializers/metrics.py
- django_project/frontend/src/containers/MainPage/Metrics/ActivityDonutChart.tsx
- django_project/frontend/src/containers/MainPage/Metrics/index.tsx
- django_project/frontend/static_mapping.py
- django_project/frontend/tests/test_metrics.py
- django_project/frontend/utils/metrics.py
This PR is for #845 
Before:
After:
> Fix activity percentage chart

- django_project/frontend/templates/account/forgot_password_reset.html
- django_project/frontend/templates/account/password_reset.html
- django_project/frontend/tests/test_map.py
- django_project/sawps/tests/test_user.py
- django_project/sawps/views.py
> Forgot password cleanup

- django_project/frontend/src/containers/MainPage/Upload/SpeciesUploader.tsx
- django_project/population_data/models.py
- django_project/species/api_views/upload_species.py
- django_project/species/tasks/upload_species.py
- django_project/species/test_api_views.py
- django_project/species/urls.py
> Add alert message in upload

- django_project/frontend/templates/navibar.html
[Screencast from 22-08-23 16:12:19.webm](https://github.com/kartoza/sawps/assets/70011086/44fa879f-6dd7-442f-ba5e-e06dba9b6890)
> patch: user menu clean ups #828

- django_project/frontend/api_views/metrics.py
- django_project/frontend/serializers/metrics.py
- django_project/frontend/src/containers/MainPage/Metrics/AgeGroupBarChart.tsx
- django_project/frontend/src/containers/MainPage/Metrics/index.scss
- django_project/frontend/src/containers/MainPage/Metrics/index.tsx
- django_project/frontend/tests/test_metrics.py
- django_project/frontend/urls.py
- django_project/frontend/utils/metrics.py
This PR is for #853 
Before : 
After:
> Feature age group chart

- django_project/frontend/src/containers/MainPage/Upload/SpeciesUploader.tsx
https://github.com/kartoza/sawps/assets/12623986/a5e1ee41-99c5-4012-a94f-36b178d0ea25
> Update event after removing file

- django_project/frontend/serializers/metrics.py
- django_project/frontend/src/containers/MainPage/Metrics/AgeGroupBarChart.tsx
- django_project/frontend/src/containers/MainPage/Metrics/index.tsx
This PR is for the issue #871
Before: 
After:
> Added female colour with transparency

- django_project/frontend/serializers/metrics.py
- django_project/frontend/src/containers/MainPage/Metrics/ActivityDonutChart.tsx
- django_project/frontend/src/containers/MainPage/Metrics/index.tsx
> Update icon field

- django_project/frontend/src/components/Loading/index.tsx
- django_project/frontend/src/containers/MainPage/Metrics/AgeGroupBarChart.tsx
- django_project/frontend/src/containers/MainPage/Metrics/ChartCard.tsx
- django_project/frontend/src/containers/MainPage/Metrics/DensityBarChart.tsx
- django_project/frontend/src/containers/MainPage/Metrics/PopulationCategoryChart.tsx
- django_project/frontend/src/containers/MainPage/Metrics/PropertyAvailable.tsx
- django_project/frontend/src/containers/MainPage/Metrics/PropertyType.tsx
- django_project/frontend/src/containers/MainPage/Metrics/SpeciesLineChart.tsx
- django_project/frontend/src/containers/MainPage/Metrics/index.scss
- django_project/frontend/src/containers/MainPage/Metrics/index.tsx
- django_project/frontend/static/css/style.css
> Use grids to display the charts

- django_project/frontend/templates/account/password_reset.html
Description:
The password reset text has been updated to read: "Dear user, we have sent you an email containing instructions to reset your password."If you have not received the email, we kindly request you to verify that the email address used for registration is correct and to review your spam."
> patch: update reset password text

- django_project/frontend/api_views/metrics.py
- django_project/frontend/serializers/metrics.py
- django_project/frontend/src/containers/MainPage/Metrics/ActivityDonutChart.tsx
- django_project/frontend/src/containers/MainPage/Metrics/AreaAvailableLineChart.tsx
- django_project/frontend/src/containers/MainPage/Metrics/index.scss
- django_project/frontend/src/containers/MainPage/Metrics/index.tsx
- django_project/frontend/static_mapping.py
- django_project/frontend/tests/test_metrics.py
- django_project/frontend/urls.py
- django_project/species/factories.py
This PR is for #852 
Before :
After:
> Integration feature area line chart

- django_project/frontend/src/components/PropertySummaryTable/index.tsx
Fix cannot access online form page.
> Fix null error when checking local storage item

- django_project/frontend/src/containers/MainPage/Metrics/ActivityDonutChart.tsx
- django_project/frontend/src/containers/MainPage/Metrics/AgeGroupBarChart.tsx
- django_project/frontend/src/containers/MainPage/Metrics/DensityBarChart.tsx
- django_project/frontend/src/containers/MainPage/Metrics/index.tsx
This PR is for #836
Before:-
After:-
Before:-
After:-
Before:-
After
> Fixes for chart layouts

- django_project/frontend/api_views/statistical.py
- django_project/frontend/serializers/national_statistics.py
- django_project/frontend/src/components/LandingPage/LandingPagePopulationOverview/OverviewCardsHolder/index.tsx
- django_project/frontend/src/components/LandingPage/LandingPagePopulationOverview/SpeciesCard/index.test.tsx
- django_project/frontend/src/components/LandingPage/LandingPagePopulationOverview/SpeciesCard/index.tsx
- django_project/frontend/src/components/PdfReport/CustomFirstPageCard.tsx
- django_project/frontend/src/components/PdfReport/FirstPageContent.tsx
- django_project/frontend/utils/statistical_model.py
- django_project/species/serializers.py
- django_project/species/test_species_models.py
> update species front page total area

- django_project/frontend/src/containers/MainPage/Metrics/ChartCard.tsx
This PR is for #915
Before:-
After:-
> Fix-typography

- django_project/frontend/static/css/style.css
- django_project/frontend/templates/allauth_2fa/backup_tokens.html
- django_project/frontend/templates/navibar.html
- django_project/frontend/templates/organisations.html
- django_project/frontend/templates/profile.html
- django_project/frontend/templates/profile_config_base.html
- django_project/frontend/templates/reminders.html
- django_project/frontend/templates/users.html
[Screencast from 05-09-23 06:48:10.webm](https://github.com/kartoza/sawps/assets/70011086/d748d50c-4c08-4f24-94ff-6a80e9258355)
[Screencast from 05-09-23 06:56:52.webm](https://github.com/kartoza/sawps/assets/70011086/fd9f1eb9-5e01-4707-a691-0d8e4da50ced)
Description:
request organisation has been moved to organisations page
all the requirements of issue #937 have been fulfilled
> Styling fixes

- django_project/frontend/api_views/property.py
> Fix property list API

- django_project/frontend/templates/help.html
Description:
the titles of both pages were the same
> patch: adjust page title

- django_project/frontend/src/containers/MainPage/MainPage.tsx
- django_project/frontend/templates/account/login.html
- django_project/frontend/templates/navibar.html
- django_project/frontend/templates/profile.html
- django_project/frontend/templates/reminders.html
- django_project/frontend/tests/test_map_view.py
- django_project/frontend/urls.py
- django_project/frontend/views/map.py
[Screencast from 11-09-2023 14:32:46.webm](https://github.com/kartoza/sawps/assets/70011086/2a05d9a8-dee8-4b1e-abbc-51ac01481fb5)
Description:
removed the upload tab from the tabs on the maps page
created upload data link in the navibar
renamed map to explore
moved remember me text to the left
changed const vars to normal var to fix error on edit reminders
> Tinashechiraya patch 8

- django_project/frontend/templates/navibar.html
> rename map to explore in navbar

- django_project/frontend/api_views/data_table.py
- django_project/frontend/src/containers/MainPage/Data/index.tsx
- django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
- django_project/frontend/static_mapping.py
- django_project/frontend/tests/test_data_table.py
- django_project/frontend/utils/data_table.py
This PR is for #789 
**Regional data consumer**
> Feature data table national

- docs/mkdocs-base.yml
> addition of page to navigation and removal of a dummy file.

- docs/mkdocs-base.yml
> Docs: adding image resize capabilities.

- django_project/frontend/api_views/upload.py
- django_project/frontend/src/assets/styles/index.scss
- django_project/frontend/tests/test_upload.py
- django_project/frontend/utils/upload_file.py
This is for https://github.com/kartoza/sawps/issues/807.
The shp files are not in root directory but there is no error message displayed in the UI. I have added the error message as below:
> Fix shape file upload issue

- django_project/frontend/utils/map.py
> Change selected parcel highlighted color to white

- django_project/frontend/src/containers/MainPage/Metrics/ActivityDonutChart.tsx
- django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
> Fixes for data tab filter

- django_project/frontend/api_views/population.py
- django_project/frontend/src/containers/OnlineFormPage/Forms/FormWizard.tsx
- django_project/frontend/src/containers/OnlineFormPage/Forms/ReviewAndConfirm.tsx
- django_project/frontend/src/containers/OnlineFormPage/Forms/SpeciesDetail.tsx
- django_project/frontend/src/models/Upload.ts
- django_project/frontend/tests/test_population.py
- django_project/population_data/models.py
- django_project/population_data/serializers.py
- django_project/population_data/test_population_data_models.py
> certainties dropdown list from table

- django_project/frontend/src/containers/MainPage/MainPage.tsx
- django_project/frontend/src/containers/MainPage/SideBar/LayerFilterTabs.tsx
- django_project/frontend/src/containers/MainPage/SideBar/LeftSideBar.tsx
- django_project/frontend/src/containers/MainPage/SideBar/index.scss
> remove layers in non-explore tabs

- django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
This PR is for #1006 and for #1020.
Before:-
After:-
> Added radio button with collapse

- django_project/frontend/tests/test_data_table.py
- django_project/frontend/utils/data_table.py
- django_project/species/views.py
This PR is for issue #1033.
Before:- 
After:-
> Fix repeating species issue

- django_project/frontend/api_views/property.py
- django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
- django_project/species/views.py
- django_project/stakeholder/views.py
This PR is for issue #1008
Before:-
After:-
> Alpgbetical order

- django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
This PR is for #1007 
Before:
After :
> Added select all option

- django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
- django_project/frontend/src/containers/MainPage/SideBar/index.scss
This PR is for #1021 
Before:
After :
> Added search bar on species

- django_project/frontend/src/containers/MainPage/Data/index.tsx
- django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
> Fixes for activity report

- django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
This PR is for issue #1043 
Before:-
After:-
> Remove badges

- django_project/frontend/src/components/LandingPage/LandingPageBanner/LandingPageBannerImage/index.tsx
- django_project/frontend/templates/help.html
Description:
the component styles were interfering with displaying the background image but setting them directly on the component resolved the issue
https://github.com/kartoza/sawps/assets/70011086/c6c5f958-2e75-4150-9294-ca86bdea1ac7
Description:
when the screen changes the page was not responsive . this has been resolved
> Main dashboard picture and help page updates

- django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
This PR is for the issue #1042
I will make the filter simple in upcoming PR
Before:-
After:-
> Fix-multiselect-tags

- django_project/frontend/templates/emails/invitation_email.html
- django_project/frontend/templates/emails/password_reset.html
- django_project/frontend/templates/emails/reminder_email.html
- django_project/frontend/templates/emails/request_organisation_email.html
Description:
the email templates have been adjusted to meet the requirements
> Email templates adjustments

- django_project/frontend/src/containers/MainPage/Data/index.scss
This PR is for the Issue #1053 
Before:- 
After:-
> UI fixes for filters for long names.

- django_project/frontend/filters/metrics.py
- django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
- django_project/frontend/tests/test_data_table.py
- django_project/frontend/tests/test_metrics.py
- django_project/frontend/utils/data_table.py
- django_project/species/serializers.py
- django_project/species/test_species_models.py
- django_project/species/views.py
This PR is for the Issue #1044.
Before:-
After:-
> Species filter by scientific name

- django_project/frontend/templates/emails/reminder_email.html
- django_project/frontend/templates/emails/request_organisation_email.html
The emails will look like this 
the logo and the variables will be replaced by the actual data coming from the backend
> Email templates fixes

- django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
- django_project/frontend/src/containers/MainPage/SideBar/index.scss
- django_project/frontend/templates/base.html
- django_project/frontend/templates/navibar.html
This PR is for the issue #1074 
Before:-
After:-
> Simple filter UI

- django_project/frontend/src/components/PdfReport/index.scss
- django_project/frontend/src/containers/MainPage/Metrics/index.scss
- django_project/frontend/src/containers/MainPage/Metrics/index.tsx
This PR is for issue #1018
Before:- 
After:-
> Fix UI issue for half charts

- django_project/frontend/src/containers/MainPage/MainPage.tsx
- django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
This PR is for the issue #1073
Before:-
After:-
> Change data tab name to reports

- django_project/sawps/admin.py
[Screencast from 26-09-2023 13:55:53.webm](https://github.com/kartoza/sawps/assets/70011086/cdbb965d-d1a4-4239-99a0-9b179e890336)
Description
I have customized the display for the static devices model
now the user will be able to search and also review additional information in the columns that I have added :
the username , name of device , status of device
> patch: make 2fa environment user friendly #972

- django_project/frontend/src/containers/MainPage/SideBar/LayerFilterTabs.tsx
[Screencast from 27-09-2023 04:03:47.webm](https://github.com/kartoza/sawps/assets/70011086/5b06cfd4-3170-4e8b-84c2-8c9d93603a62)
Description:
now select and digitise work as expected
> patch: fix select property or digitise not working #1116

- django_project/frontend/templates/contact.html
Description:
the contact us form's positioned has been adjusted
and page made responsive
> patch: adjust contact us dialogue #966

- django_project/frontend/api_views/data_table.py
- django_project/frontend/static_mapping.py
- django_project/frontend/templates/organisations.html
- django_project/frontend/templates/users.html
- django_project/frontend/templatetags/custom_tags.py
- django_project/frontend/tests/test_data_table.py
- django_project/frontend/tests/test_templatetags.py
- django_project/frontend/utils/data_table.py
- django_project/frontend/views/users.py
This reverts commit 721ff14a274d380203680fddf511f9e54a94675e.
> Revert "Add templatetag function to check if user is a manager (#1112)"

- django_project/frontend/src/containers/MainPage/index.scss
This PR is for the issue #1038 
Before:- 
After:-
37/559f3643-cb73-4243-8ae1-0a01dc6972a3)
> Fix table title cut issue

- django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
- django_project/frontend/static_mapping.py
This PR is fo issue #1143 
Before:-
After:-
> Fix Sampling report issue

- django_project/frontend/api_views/data_table.py
- django_project/frontend/src/reducers/SpeciesFilter.ts
This PR is for the issue #1066 
Before:- 
After:-
> Organisation issue fix

- django_project/frontend/api_views/data_table.py
- django_project/frontend/templates/account/password_change.html
- django_project/frontend/templates/allauth_2fa/backup_tokens.html
- django_project/frontend/templates/base.html
- django_project/frontend/templates/notifications.html
- django_project/frontend/templates/organisations.html
- django_project/frontend/templates/profile.html
- django_project/frontend/templates/reminders.html
- django_project/frontend/templates/users.html
- django_project/frontend/tests/test_map_view.py
- django_project/frontend/urls.py
- django_project/frontend/views/map.py
issue #1152 
Description:
I have made the footer visible by default without using the vertical scroll on profile pages
I have added an even spacing on the 2fa page
I have positioned the footer correctly on the update password page
I have adjusted the positioning of the footer contents to fit the footer nicely
I have added responsiveness to the users page
I have fixed a bug on reloading the reports page
> Styling improvements

- django_project/frontend/serializers/metrics.py
- django_project/frontend/src/containers/MainPage/Metrics/ActivityBarChart.tsx
- django_project/frontend/src/containers/MainPage/Metrics/SpeciesSideBarLineChart.tsx
- django_project/frontend/src/containers/MainPage/Property/PropertySummary.tsx
- django_project/frontend/templates/account/password_change.html
- django_project/frontend/templates/allauth_2fa/backup_tokens.html
- django_project/frontend/templates/notifications.html
- django_project/frontend/templates/organisations.html
- django_project/frontend/templates/profile.html
- django_project/frontend/templates/reminders.html
[Screencast from 02-10-2023 21:16:52.webm](https://github.com/kartoza/sawps/assets/70011086/8a55dfd1-69f4-4d04-a03b-902d2afb9a1f)
Description:
the filters are now linked to the data that is displayed on the right side bar panel
adjusting any filter will cause the charts to refresh fetching the data with the selected parameters
I have also fixed the charts not returning any data at all
> Update charts on sidebar panel property information

- django_project/frontend/src/containers/AboutPage/index.scss
- django_project/frontend/src/containers/MainPage/Data/index.scss
- django_project/frontend/static/css/style.css
- django_project/frontend/templates/about.html
- django_project/frontend/templates/help.html
This PR is for #1163 #1164 #1165
> Fixes for help and about page

- django_project/frontend/src/containers/AboutPage/index.scss
- django_project/frontend/static/css/style.css
- django_project/frontend/templates/about.html
- django_project/frontend/templates/contact.html
This is PR for #1163 #1165 Feedback and Contact page responsive 
Made it responsive
About page : 
https://github.com/kartoza/sawps/assets/138113337/31078a04-3e16-4634-9f0a-2870f8e785c3
Contact page:
https://github.com/kartoza/sawps/assets/138113337/ddd87cb7-070e-4c42-9072-3ca1b10095af
> added about page responsive

- django_project/frontend/serializers/metrics.py
- django_project/frontend/src/containers/MainPage/Metrics/AgeGroupBarChart.tsx
- django_project/frontend/tests/test_metrics.py
[Screencast from 04-10-2023 14:48:42.webm](https://github.com/kartoza/sawps/assets/70011086/9281defa-94a4-4c2d-a0ca-5f49773db572)
Description:
the chart has been updated:
its now stacked 
the legend values are the species groups (adult male, sub adult etc)
by default the chart fetches the years where data is available
adjusting the filter values will refresh the chart to fetch new data
the colors in graph matrix have been implemented
the chart style in the graph matrix has been implemented
> Species population per age group

- django_project/frontend/src/containers/MainPage/Data/index.tsx
- django_project/frontend/src/containers/MainPage/index.scss
> Fixes horizontal scroll for reports

- django_project/frontend/utils/data_table.py
This PR is for issue #1195 
Before:- 
After:-
> Fix data table API

- django_project/frontend/src/containers/MainPage/Metrics/AgeGroupBarChart.tsx
- django_project/frontend/src/containers/MainPage/Metrics/AreaAvailableLineChart.tsx
- django_project/frontend/src/containers/MainPage/Metrics/DensityBarChart.tsx
- django_project/frontend/src/containers/MainPage/Metrics/PropertyType.tsx
- django_project/frontend/src/containers/MainPage/Metrics/index.tsx
- django_project/frontend/utils/metrics.py
[Screencast from 06-10-2023 10:00:56.webm](https://github.com/kartoza/sawps/assets/70011086/81f13887-4034-468d-994d-0e8a27c61c40)
Description:
I have made the styling consistent (all labels are bold now)
I have added the tooltip to each chart that supports a tooltip
I have added the total area per property type chart which will show the area occupied by a certain property
> Total property area and UI updates

- django_project/frontend/src/containers/MainPage/Metrics/AgeGroupBarChart.tsx
- django_project/frontend/src/containers/MainPage/Metrics/AreaAvailableLineChart.tsx
- django_project/frontend/src/containers/MainPage/Metrics/PropertyType.tsx
- django_project/frontend/src/containers/MainPage/Metrics/index.tsx
Description:
I have adjusted the height and width of other charts so they match
I have updated the position of the download button ,it will now be fixed in the bottom right corner
I have adjusted the property type chart to use property type name in legend labels and tooltip to show property name
> Adjust charts styling

- django_project/species/scripts/data_upload.py
- django_project/species/test_api_views.py
> Move the error_message to the first column

- django_project/frontend/utils/data_table.py
Finalizing the report.
Before:- 
After:-
> Show names instead of id

- django_project/frontend/src/containers/MainPage/Data/index.tsx
- django_project/frontend/src/containers/MainPage/index.scss
This PR is for fix the scroll for the Reports Table
> Fixes width for scroll for Reports Table

- django_project/frontend/src/containers/AboutPage/index.scss
- django_project/frontend/static/css/style.css
- django_project/frontend/templates/about.html
This PR is for issue #1234
@amyburness, The `About` page looks like this at 100% screen size.
https://github.com/kartoza/sawps/assets/138113337/3bb836f7-e7d7-45df-9285-8e01e0ca67c4
> fix-move-pg-element-up

- django_project/frontend/static/css/style.css
- django_project/frontend/templates/account/login.html
- django_project/frontend/templates/account/logout.html
- django_project/frontend/templates/account/signup.html
- django_project/frontend/templates/allauth_2fa/authenticate.html
This PR is for #1233 
Two-Factor authentication form has also moved I have fixed that one also
cc : @amyburness 
Before :
**Register Page**
**Login Page**
**Two-Factor authentication Page**
**Logout Page**
After :
**Register Page**
**Login Page**
**Two-Factor authentication Page**
**Logout Page**
> Fixes for forms UI

- django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
> fixes collapse issue on property select

- django_project/sawps/admin.py
- django_project/sawps/models.py
- django_project/sawps/tests/test_model.py
- django_project/sawps/tests/test_utils.py
- django_project/sawps/utils.py
Some information below on the code
> Fix the issue of duplicate groups being created from the admin panel

- django_project/frontend/src/containers/MainPage/Metrics/PopulationEstimateCategory.tsx
- django_project/frontend/src/containers/MainPage/Metrics/PopulationEstimateCategoryAsPercentage.tsx
- django_project/frontend/src/containers/MainPage/Metrics/SpeciesCountAsPercentage.tsx
- django_project/frontend/src/containers/MainPage/Metrics/TotalCountPerActivity.tsx
Description:
I picked up an error on sentry https://sentry.kartoza.com/kartoza/sanbi-wps/issues/4194/?query=is%3Aunresolved
I have resolved the issue
> Tinashechiraya patch 11

- django_project/activity/models.py
- django_project/frontend/api_views/data_table.py
- django_project/frontend/serializers/report.py
- django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
- django_project/frontend/src/reducers/SpeciesFilter.ts
- django_project/frontend/src/services/api.ts
- django_project/frontend/tests/test_data_table.py
- django_project/frontend/utils/data_table.py
This is PR for #1311
I updated Activity filters to use autocomplete checkbox dropdown, and adjust datatable API.
[Kazam_screencast_00032.webm](https://github.com/kartoza/sawps/assets/7352963/8ecd800c-eafc-4d76-8ecb-2201c43799cf)
> Feature/1311: filter activity multiple

- django_project/frontend/src/containers/MainPage/Metrics/ActivityBarChart.tsx
- django_project/frontend/src/containers/MainPage/Metrics/SpeciesSideBarLineChart.tsx
[Screencast from 18-10-2023 19:21:35.webm](https://github.com/kartoza/sawps/assets/70011086/5bde52d7-a33d-47a5-bd5c-721a25193219)
I have updated the sidebar panel charts to work with filter selections 
and also to use the same style with other charts where
the chart is interactive (tooltip,labels,legend)
> Update sidebar panel charts on map

- deployment/docker/requirements.txt
- django_project/core/settings/contrib.py
- django_project/core/urls.py
- django_project/frontend/package-lock.json
- django_project/frontend/package.json
- django_project/frontend/src/containers/HelpPage/Help.tsx
- django_project/frontend/src/containers/HelpPage/index.scss
- django_project/frontend/templates/help.html
This fix https://github.com/kartoza/sawps/issues/1014
Hi @timlinux @dimasciput @amyburness 
I have put thelp system to sanbi
Example:
The react component is in here: https://github.com/kartoza/django-docs-crawler-react
Django component is in here : https://github.com/kartoza/django-docs-crawler
> Use help system

- django_project/frontend/src/components/Footer/index.tsx
- django_project/frontend/templates/base.html
This PR is for issue #1302 #1335
https://github.com/kartoza/sawps/assets/138113337/4daa713e-f83a-4631-8305-d09e62f686ce
> Update documentation link

- django_project/frontend/templates/about.html
This PR is for issue #1334
Before:-
After:-
> Update about page video

- django_project/frontend/templates/base.html
This PR is for the issue #1392
> Added links to the footer logos

- django_project/frontend/static/css/style.css
- django_project/frontend/templates/account/account_inactive.html
- django_project/frontend/templates/account/forgot_password_reset.html
- django_project/frontend/templates/account/password_reset.html
This PR is for issue #1378
Before:-
After:-
> Ui fixes for popups

- django_project/frontend/src/components/Footer/index.tsx
- django_project/frontend/templates/base.html
This PR is for the issue #1401 
https://github.com/kartoza/sawps/assets/138113337/80065a0b-08ca-4c77-93c3-2feac89adb50
> Fix footer issue

- django_project/frontend/api_views/metrics.py
- django_project/frontend/src/containers/MainPage/Metrics/PropertyType.tsx
- django_project/frontend/tests/test_metrics.py
- django_project/frontend/utils/metrics.py
[Screencast from 22-10-2023 09:22:50.webm](https://github.com/kartoza/sawps/assets/70011086/01728ab5-b661-4e43-84ef-cdc663333124)
Description:
as requested the property type will now return properties that have a species selected in the filters on them
> patch: update test for total area per property type #1363

- django_project/frontend/tests/test_map_view.py
- django_project/frontend/urls.py
- django_project/frontend/views/map.py
This is PR for #1402
Screen record:
[Kazam_screencast_00035.webm](https://github.com/kartoza/sawps/assets/7352963/f10f76b8-5615-46d8-8b65-b35a925f4c86)
> Fix/1402: trend page and upload page

- django_project/frontend/e2e/about.spec.ts
- django_project/frontend/templates/about.html
This PR is for issue #1400 
Before:- 
After:-
> UI changes for the about page

- django_project/frontend/src/components/Footer/index.tsx
- django_project/frontend/templates/base.html
This PR is for issue #1423 
Before:-
After:-
> Remove EXPLORE prior to login

- django_project/frontend/utils/metrics.py
This is to fix lint error in other PRs, could you merge this first then I'll push to my other PRs @dimasciput?
> fix lint error in metrics functions

- django_project/frontend/templates/about.html
- django_project/frontend/templates/account/forgot_password_reset.html
- django_project/frontend/templates/account/login.html
- django_project/frontend/templates/account/logout.html
- django_project/frontend/templates/account/password_reset.html
- django_project/frontend/templates/account/signup.html
- django_project/frontend/templates/allauth_2fa/authenticate.html
- django_project/frontend/templates/base.html
- django_project/frontend/templates/contact.html
- django_project/frontend/templates/profile.html
- django_project/sawps/tests/test_user.py
This PR is for issue #1337 
Before:- 
After:- 
Note: The title will be the same for all tabs.
> Fix title issue

- django_project/frontend/e2e/about.spec.ts
- django_project/frontend/templates/reminders.html
This PR is for issue #1418 
Before:-
After:-
> Changes error messages

- django_project/frontend/src/containers/OnlineFormPage/Forms/ReviewAndConfirm.tsx
- django_project/frontend/src/containers/OnlineFormPage/Forms/SpeciesDetail.tsx
- django_project/frontend/src/models/Upload.ts
> add subpopulation total in online forms

- django_project/frontend/serializers/metrics.py
- django_project/frontend/src/components/PdfReport/PopulationCategoryChart.tsx
- django_project/frontend/src/containers/MainPage/Metrics/PopulationCategoryChart.tsx
- django_project/frontend/src/containers/MainPage/Metrics/TotalCountPerActivity.tsx
- django_project/frontend/src/containers/MainPage/Metrics/index.tsx
- django_project/frontend/tests/test_population_categories.py
- django_project/frontend/tests/test_population_count_per_province.py
- django_project/frontend/utils/metrics.py
for https://github.com/kartoza/sawps/issues/990
> Update population category chart

- django_project/population_data/admin.py
This PR is for issue #1460 
Before:-
After:-
> Admin annualpopulation per activity UI

- django_project/population_data/admin.py
This PR is for issue #1187 
Before:-
After:-
> Annualpopulation UI

- django_project/population_data/admin.py
This PR is for the issue #1487
> Fix annualpopulation issue

- django_project/frontend/src/components/Button/index.tsx
- django_project/frontend/src/components/ChartContainer/index.tsx
- django_project/frontend/src/components/ChartContainer/style.scss
- django_project/frontend/src/components/DoughnutChart/index.tsx
- django_project/frontend/src/containers/MainPage/Metrics/PopulationEstimateCategory.tsx
- django_project/frontend/src/containers/MainPage/Metrics/TotalCountPerActivity.tsx
- django_project/frontend/src/containers/MainPage/Metrics/index.tsx
Updates:
- Created the ChartContainer component. To-do: Wrap all charts within this component.
- Created the DoughnutChart component. To-do: Update the remaining doughnut charts to use this component.
> Improve doughnut chart

- django_project/frontend/src/components/SideBar/index.tsx
- django_project/frontend/src/containers/MainPage/Data/index.scss
- django_project/frontend/src/containers/MainPage/Data/index.tsx
- django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
This is PR for #1390, #1391, #1393, #1394, #1430
The screen recording is in the tickets.
> feature/1390-1391-1393-1394-1430: Filter Issue

- django_project/frontend/src/containers/MainPage/Metrics/index.tsx
This is PR for #1278 
Topper is added to chats.
> feature/1278: Add topper to charts

- django_project/frontend/src/containers/MainPage/Data/index.tsx
This is PR for #1338 
Now filtering columns will also work when only Activity Report is shown.
> feature/1338: Add Activity Data filter columns

- django_project/frontend/src/containers/MainPage/Map/MapUtility.ts
- django_project/frontend/src/containers/MainPage/Map/index.tsx
> Add 3d layer based on province/properties count

- deployment/plumber/Dockerfile
- django_project/frontend/api_views/data_table.py
- django_project/frontend/api_views/metrics.py
- django_project/frontend/serializers/report.py
- django_project/frontend/src/containers/MainPage/Metrics/SpeciesCountAsPercentage.tsx
- django_project/frontend/src/containers/MainPage/Metrics/index.tsx
- django_project/frontend/tests/test_data_table.py
- django_project/frontend/tests/test_population_count_per_province.py
- django_project/frontend/utils/data_table.py
- django_project/frontend/utils/metrics.py
This is PR for #1214 #1426
The chart and report previously only showed Free State.
Now it also shows Western Cape.
> Fix/1214-1426: inconsistent province report data

- django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
- docs/src/user/manual/explore/filters.md
This is PR for #1508 
I add docs for Filter permission.
> fix/1508: Remove property filter permission checking

- django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
- django_project/frontend/src/services/api.ts
- django_project/frontend/tests/test_serializers.py
> feature/1421: Add shortcode to property dropdown

- django_project/frontend/src/containers/MainPage/Data/index.scss
- django_project/frontend/src/containers/MainPage/Data/index.tsx
This is PR for #1543
Sample PDF:
[Acinonyx jubatus - reports.pdf](https://github.com/kartoza/sawps/files/13290963/Acinonyx.jubatus.-.reports.pdf)
> feature/1543: Add PDF exporter

- django_project/frontend/templates/about.html
- django_project/frontend/templates/account/account_inactive.html
- django_project/frontend/templates/account/forgot_password_reset.html
- django_project/frontend/templates/account/login.html
- django_project/frontend/templates/account/logout.html
- django_project/frontend/templates/account/password_change.html
- django_project/frontend/templates/account/password_reset.html
- django_project/frontend/templates/account/signup.html
- django_project/frontend/templates/allauth_2fa/authenticate.html
- django_project/frontend/templates/allauth_2fa/backup_tokens.html
- django_project/frontend/templates/allauth_2fa/setup.html
- django_project/frontend/templates/contact.html
- django_project/frontend/templates/help.html
- django_project/frontend/templates/notifications.html
- django_project/frontend/templates/online_form.html
- django_project/frontend/templates/organisations.html
- django_project/frontend/templates/profile.html
- django_project/frontend/templates/reminders.html
- django_project/frontend/templates/users.html
> Make title same for all pages

- django_project/frontend/src/containers/MainPage/Map/MapUtility.ts
> Fix null map object

- django_project/frontend/src/containers/OnlineFormPage/Forms/SpeciesDetail.tsx
- django_project/species/scripts/data_upload.py
- django_project/species/test_api_views.py
Preview:
Also applied to error message for excel upload.
> Fix error message validation area available to species

- django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
- django_project/frontend/src/containers/MainPage/SideBar/index.scss
This is PR for #1535 
[Kazam_screencast_00050.webm](https://github.com/kartoza/sawps/assets/7352963/de53de7d-97af-4021-a6dd-044942fa1ea8)
> fix/1535: Fix year filter

- django_project/frontend/src/containers/MainPage/Metrics/ActivityBarChart.tsx
This is for #1315.
Preview:
Data
> fix activity bar chart in property summary

- django_project/frontend/src/containers/MainPage/Upload/SpeciesUploader.tsx
- django_project/species/api_views/upload_species.py
- django_project/species/tasks/upload_species.py
This is for #1504. Also to fix fetch upload status timer
> Reusing upload session 

- django_project/frontend/api_views/map.py
- django_project/frontend/src/containers/MainPage/Map/index.tsx
- django_project/frontend/tests/test_map.py
- django_project/frontend/utils/map.py
- django_project/species/test_api_views.py
This is for #1580 part of #1574
> Remove filter_start_year from map query

- django_project/frontend/api_views/property.py
- django_project/frontend/serializers/property.py
- django_project/frontend/tests/test_property.py
This is part of #1420 - adding property short code in the search result and enable search by property short code.
> Search property by short_code

- django_project/frontend/templates/account/password_reset.html
- django_project/sawps/tests/test_user.py
- django_project/sawps/views.py
For https://github.com/kartoza/sawps/issues/1592
> Fix reset password for non registered email

- django_project/frontend/templates/users.html
- django_project/frontend/views/users.py
> Fix cant invite people to organisation

- django_project/frontend/src/containers/MainPage/Data/index.tsx
- django_project/frontend/src/containers/MainPage/index.scss
> Fix/1607: Province report column widt

- django_project/frontend/src/containers/MainPage/Data/Topper.tsx
- django_project/frontend/src/containers/MainPage/Trends/index.tsx
> feature/1616: Add trends page topper

- django_project/frontend/api_views/metrics.py
- django_project/frontend/serializers/metrics.py
- django_project/frontend/tests/test_metrics.py
This is PR for updating population density chart to use area available to species.
> Update population density charts

- django_project/frontend/src/containers/MainPage/MainPage.tsx
- django_project/frontend/src/containers/MainPage/index.scss
> Fix scroll in maps and reports

- playwright/staging-tests/record-test.sh
> minor fix - staging script

- django_project/frontend/api_views/statistical.py
- django_project/frontend/src/components/LandingPage/LandingPagePopulationOverview/SpeciesChart/index.tsx
- django_project/frontend/src/containers/MainPage/Trends/GroupedGrowthChart.tsx
- django_project/frontend/src/containers/MainPage/Trends/GrowthChart.tsx
- django_project/frontend/src/containers/MainPage/Trends/NationalTrendSection.tsx
- django_project/frontend/src/containers/MainPage/Trends/PopulationTrendChart.tsx
- django_project/frontend/src/containers/MainPage/Trends/PropertyTrendSection.tsx
- django_project/frontend/src/containers/MainPage/Trends/ProvincialTrendSection.tsx
- django_project/frontend/src/containers/MainPage/Trends/index.scss
- django_project/frontend/src/containers/MainPage/Trends/index.tsx
- django_project/frontend/tests/test_api_statistical.py
- django_project/frontend/urls.py
- django_project/frontend/utils/plumber_template.R
This is for #1168, #1169, #1170
Previews:
> Update trends chart

- django_project/frontend/static/css/style.css
This PR is for issue #1665 
Before:-
After:-
> Fix footer

- django_project/frontend/src/assets/styles/index.scss
- django_project/frontend/src/containers/MainPage/index.scss
- django_project/frontend/src/containers/OnlineFormPage/index.scss
> fix scrolling in app container

- django_project/frontend/src/containers/MainPage/Metrics/index.tsx
> feature/1620: Remove some charts

- django_project/frontend/tests/test_population_count_per_province.py
- django_project/frontend/utils/metrics.py
This is PR for #1630
The population per province is now consistent between charts and reports
> Fix/1630: Population count per province chart

- django_project/frontend/src/components/FeedbackAlertDialog/index.tsx
- django_project/frontend/src/containers/OnlineFormPage/Forms/FormWizard.tsx
> add another record button in success dialog

- django_project/frontend/src/containers/MainPage/Map/LegendControl.tsx
- django_project/frontend/src/containers/MainPage/Map/index.tsx
> add year to map legend title

- django_project/frontend/src/containers/MainPage/Trends/GrowthChart.tsx
- django_project/frontend/src/containers/MainPage/Trends/NationalTrendSection.tsx
- django_project/frontend/src/containers/MainPage/Trends/PropertyTrendSection.tsx
- django_project/frontend/src/containers/MainPage/Trends/ProvincialTrendSection.tsx
- django_project/frontend/src/utils/Helpers.ts
> Trends UI fixes

- django_project/frontend/api_views/metrics.py
- django_project/frontend/serializers/metrics.py
- django_project/frontend/src/containers/MainPage/Metrics/ActivityBarChart.tsx
- django_project/frontend/src/containers/MainPage/Metrics/SpeciesSideBarChart.tsx
- django_project/frontend/src/containers/MainPage/Property/PropertySummary.tsx
- django_project/frontend/tests/test_metrics.py
- django_project/frontend/tests/test_utils_organisation.py
- django_project/frontend/urls.py
- django_project/frontend/utils/organisation.py
> Fix sidebar charts

- docs/src/user/manual/user-roles.md
This PR is for the issue #1657
> Update user role documentation

- docs/src/user/manual/explore/map.md
This PR is for the map documentation update.
> Update map doc

- django_project/frontend/src/containers/MainPage/Metrics/index.tsx
> feature/1742: Change chart order

- django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
> feature/1743: Move activity filter order

- django_project/frontend/serializers/report.py
- django_project/frontend/tests/test_data_table.py
- django_project/frontend/utils/data_table.py
> feature/1746: Add total to Species report for Data Consumer.

- django_project/frontend/api_views/metrics.py
- django_project/frontend/api_views/national_statistic.py
- django_project/frontend/tests/test_national_statistics.py
- django_project/frontend/views/base_view.py
- django_project/frontend/views/switch_organisation.py
- django_project/stakeholder/tests/test_view.py
- docs/src/developer/manual/activity.md
- docs/src/developer/manual/frontend.md
- docs/src/developer/manual/population_data.md
- docs/src/developer/manual/property.md
- docs/src/developer/manual/regulator_permit.md
- docs/src/developer/manual/sawps.md
- docs/src/developer/manual/species.md
- docs/src/developer/manual/stakeholder.md
- docs/src/user/guide/organisations.md
> Add missing mkdocstring

- django_project/frontend/serializers/report.py
- django_project/frontend/src/containers/MainPage/Data/index.tsx
- django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
- django_project/frontend/utils/data_table.py
This is PR for #1747
Detailed reports
Summarized reports
> fix/1747: Fix Activity reports for national data consumer

- django_project/frontend/src/containers/MainPage/Data/index.tsx
- django_project/frontend/src/containers/MainPage/MainPage.tsx
- django_project/frontend/src/containers/MainPage/Metrics/index.tsx
- django_project/frontend/src/containers/MainPage/SideBar/LeftSideBar.tsx
- django_project/frontend/src/containers/MainPage/Trends/index.tsx
- django_project/frontend/src/containers/MainPage/index.scss
This is for #1756.
Preview:
On small screen:
> Fix scrolling area in reports, charts, trends, and filters

- django_project/species/scripts/data_upload.py
- django_project/species/test_api_views.py
> Add permission to data upload excel

- django_project/frontend/src/containers/MainPage/Map/index.tsx
- django_project/frontend/src/containers/MainPage/Property/PropertySummary.tsx
> Fix closing right panel

- django_project/frontend/tests/test_map.py
- django_project/frontend/utils/map.py
This is for #1738. Now the properties in choropleth map will only show properties that has selected activities. cc: @LunaAsefaw 
Without selected activity filter, the map shows every properties:
With selected activity filter, now only properties in Kwazulu-Natal are displayed:
> change activity filter logic in map population properties query

- django_project/frontend/src/containers/MainPage/Data/Topper.tsx
- django_project/frontend/src/containers/MainPage/Metrics/PropertyCountPerCategory.tsx
This is PR for #1805
[Kazam_screencast_00064.webm](https://github.com/kartoza/sawps/assets/7352963/3ed676e0-081c-40aa-9475-e52680057a9d)
> Fix/1805: Fix topper icon

- django_project/frontend/src/containers/MainPage/MainPage.tsx
This PR is for the context help page system.
This is a halfway task, so I am not referencing the ticket in it.
> Context help desk

- django_project/frontend/src/containers/MainPage/Trends/GrowthChart.tsx
- django_project/frontend/src/containers/MainPage/Trends/NationalTrendSection.tsx
This is for the latest requested change from new R code. After this PR is merged, we need to update the R code on staging.
TODO:
Preview:
> Add category label in national growth trends chart title

- django_project/stakeholder/models.py
- django_project/stakeholder/tests/test_stakeholder_models.py
> fix string representation not returning string of id

- django_project/frontend/src/containers/MainPage/Data/index.tsx
- django_project/frontend/tests/test_data_table.py
- django_project/frontend/utils/data_table.py
> Fix reports download issue

- django_project/population_data/models.py
- django_project/population_data/tests/test_population_data_models.py
- django_project/population_data/tests/test_utils.py
- django_project/species/models.py
> fix property object does not exist in string representation

- django_project/frontend/src/containers/MainPage/Metrics/index.tsx
This PR is for the first task of issue #1846
> Correct spelling mistake

- django_project/frontend/api_views/property.py
- django_project/frontend/src/components/SearchPlace/index.tsx
- django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
- django_project/frontend/src/containers/MainPage/Upload/index.tsx
- django_project/frontend/src/utils/SearchPlaces.ts
- django_project/frontend/tests/test_property.py
> Fix search property on explore tab

- django_project/frontend/serializers/report.py
- django_project/frontend/src/containers/MainPage/Data/index.tsx
- django_project/frontend/utils/data_table.py
> remove actions field in csv/excel species report

- deployment/docker/requirements.txt
Add uWSGI tools for checking the health check inside a uWSGI container.
> Add uwsgi-tools

- docs/src/user/manual/about.md
- docs/src/user/manual/data-upload/index.md
- docs/src/user/manual/data-upload/panel.md
- docs/src/user/manual/explore/layers.md
- docs/src/user/manual/explore/trends.md
- docs/src/user/manual/help-contact.md
- docs/src/user/manual/index.md
- docs/src/user/manual/landing-page.md
- docs/src/user/manual/login-logout/forgot-password.md
- docs/src/user/manual/register/register-page.md
- docs/src/user/manual/user-profile/2fa.md
- docs/src/user/manual/user-profile/index.md
- docs/src/user/manual/user-profile/notifications.md
- docs/src/user/manual/user-profile/organisation-page.md
- docs/src/user/manual/user-profile/profile-page.md
- docs/src/user/manual/user-profile/reminders.md
> Correct typos and minor changes

- docs/src/user/manual/explore/trends.md
> Added note for uploading file on windows

- docs/src/user/manual/data-upload/panel.md
> Update upload parcel doc

- django_project/frontend/api_views/metrics.py
- django_project/frontend/tests/test_metrics.py
- django_project/frontend/utils/metrics.py
> fix rounding of bounds from population density charts

- django_project/frontend/src/containers/MainPage/Upload/Uploader.tsx
> Add geojson file type

- django_project/frontend/templates/navibar.html
> add back the request organisation button to user menu

- django_project/core/urls.py
- django_project/frontend/accounts_urls.py
- django_project/frontend/tests/test_logout_view.py
- django_project/frontend/views/contact.py
- django_project/frontend/views/logout_view.py
This is for #1877. Also fix the Upload Data menu in logout view.
> Fix upload data link in contact and logout

- django_project/frontend/src/containers/MainPage/Metrics/TotalCountPerActivity.tsx
> Fix cutoff of activity count in chart

- django_project/stakeholder/models.py
> rename organisation tables to managers and members

- django_project/frontend/templates/navibar.html
- django_project/frontend/templates/organisations.html
- django_project/sawps/views.py
> Fix typo organisation

- django_project/frontend/tests/test_users_view.py
- django_project/frontend/views/users.py
- django_project/stakeholder/admin.py
> Show organisation member name

- django_project/species/scripts/data_upload.py
> set filter in queryset case insensitive

- django_project/frontend/utils/upload_file.py
> fix wrong srid for find_province in search boundary

- django_project/stakeholder/tasks.py
- django_project/stakeholder/tests/test_tasks.py
https://github.com/kartoza/sawps/issues/1914
> Improve send reminder emails task

- django_project/sawps/tests/test_user.py
- django_project/sawps/views.py
For https://github.com/kartoza/sawps/issues/1928
> Fix user invite function when user has no user_profile

- django_project/frontend/src/containers/MainPage/MainPage.tsx
> Fix navigation from map and upload page

- django_project/frontend/src/containers/MainPage/Data/index.tsx
> Improve loading in frontend

- django_project/frontend/views/users.py
For https://github.com/kartoza/sawps/issues/1936
> Fix members not showing up in the list

- django_project/core/urls.py
- django_project/frontend/allauth2fa_urls.py
- django_project/frontend/templates/navibar.html
- django_project/frontend/templates/users.html
- django_project/frontend/tests/test_2fa_view.py
- django_project/frontend/views/allauth_2fa.py
- django_project/frontend/views/users.py
- django_project/sawps/forms/account_forms.py
- django_project/sawps/tests/test_activate_account.py
- django_project/sawps/tests/test_user.py
- django_project/sawps/views.py
- django_project/stakeholder/models.py
- playwright/ci-test/tests/11-navbar-navigation.spec.ts
- playwright/ci-test/tests/13-upload-data-xlsx-file.spec.ts
- playwright/ci-test/tests/14-upload-data-csv-file.spec.ts
This is for:
- #1935
- #1927
- Fix bug on re-render invitation table after new invite has been submitted
> Fix onboarding organisation

- django_project/core/celery.py
- django_project/frontend/apps.py
- django_project/frontend/src/containers/MainPage/Data/index.tsx
- django_project/frontend/tasks/__init__.py
- django_project/frontend/tasks/clean_download_data.py
- django_project/frontend/tests/test_clean_download_data.py
- django_project/frontend/tests/test_data_table.py
- django_project/frontend/tests/test_frontend_config.py
- django_project/frontend/utils/data_table.py
- django_project/property/apps.py
This is for #1963.
- Fix downloader writing to same file in media directory
- Add cron job to remove temporary directory
- Add loading indicator when server is processing the request
> Fix download report issues

- django_project/frontend/templates/notifications.html
- django_project/frontend/templates/reminders.html
- django_project/stakeholder/tests/test_view.py
- django_project/stakeholder/views.py
This is for #1878. Removing filter dropdown since search text will be able to search in either title or reminder field.
Preview:
> remove filter from notification and reminders

- django_project/frontend/templates/users.html
- django_project/frontend/tests/test_users_view.py
- django_project/frontend/views/users.py
This is for #1976. Also improve the delete confirmation message to indicate removing manager or member.
> fix deletion of organisation manager

- django_project/frontend/static_mapping.py
- django_project/frontend/tests/test_map_view.py
- django_project/frontend/tests/test_online_form_view.py
> allow data scientist role to do data upload

- django_project/frontend/api_views/population.py
- django_project/frontend/src/containers/MainPage/Data/index.tsx
- django_project/frontend/tests/test_population.py
- django_project/frontend/urls.py
> Feat delete upload record

- README.md
Dynamic badges will avoid readme commits for new staging builds.
> Add dynamic badges

- django_project/frontend/src/containers/OnlineFormPage/Forms/SpeciesDetail.tsx
- django_project/frontend/src/containers/OnlineFormPage/Forms/index.scss
This is for #1974.
Preview:
Summary tab:
> fix overflow for select field in online form

- docs/src/user/manual/login-logout/login-page.md
This PR is for issue #1949 
https://github.com/kartoza/sawps/assets/138113337/04fb6ce4-510e-4db2-8383-b55ec1ad8d4e
> Update the login page doc

- django_project/frontend/templates/emails/organisation_permission_changed.html
- django_project/frontend/tests/test_organisations.py
- django_project/frontend/views/organisations.py
For https://github.com/kartoza/sawps/issues/1894
> Email the admin about any changes in the organization's data use permissions

- django_project/frontend/static/css/account_inactive.css
- django_project/frontend/static/js/account_inactive.js
- django_project/frontend/templates/account/account_inactive.html
- django_project/frontend/templates/emails/reminder_email.html
- django_project/sawps/forms/account_forms.py
- django_project/sawps/middleware.py
- django_project/sawps/tests/test_resend_verification_email.py
- django_project/sawps/urls.py
- django_project/sawps/views.py
For https://github.com/kartoza/sawps/issues/1975
> Feature: Resend Verification Email for Inactive Users

- docs/src/developer/manual/index.md
This PR is for the issue #2028
> Update developer index

- docs/src/developer/documentation/context-help.md
- docs/src/developer/documentation/index.md
- docs/src/developer/documentation/overview.md
This PR is for the issue #2035
> Update context id

- deployment/tegola/tegola.conf
- django_project/frontend/src/containers/MainPage/Map/MapUtility.ts
This is for https://github.com/kartoza/sawps/issues/1998.
Requires restoring new layer dump file, I will ask Tharanath to do it for our staging.
> Feat protected areas name

- django_project/frontend/serializers/report.py
- django_project/frontend/src/components/PropertySummaryTable/index.tsx
This is for https://github.com/kartoza/sawps/issues/2047.
> Fix property area decimal

- django_project/frontend/api_views/statistical.py
- django_project/frontend/tests/test_api_statistical.py
- django_project/frontend/tests/test_generate_statistical_model.py
- django_project/frontend/tests/test_utils_statistical.py
- django_project/frontend/utils/statistical_model.py
This is for https://github.com/kartoza/sawps/issues/2044
> update trends API to fetch from file if not exists in cache

- django_project/fixtures/population_estimate_category.json
- django_project/fixtures/population_status.json
- django_project/fixtures/sampling_effort_coverage.json
- django_project/fixtures/survey_methods.json
- django_project/frontend/admin.py
- django_project/species/scripts/data_upload.py
- django_project/species/test_api_views.py
- playwright/ci-test/tests/08-upload-online-form-1.spec.ts
- playwright/ci-test/tests/12-upload-online-form-2.spec.ts
This is for https://github.com/kartoza/sawps/issues/2027
> fix validate if value of fields does not exist in tables

- docs/src/user/manual/explore/index.md
This PR is for the issue #2058
> Add the trends tab link into the index page

- deployment/docker/requirements.txt
- django_project/frontend/api_views/statistical.py
- django_project/frontend/src/containers/MainPage/Trends/GrowthChart.tsx
- django_project/frontend/src/containers/MainPage/Trends/NationalTrendSection.tsx
- django_project/frontend/src/containers/MainPage/Trends/index.scss
- django_project/frontend/tests/test_api_statistical.py
> Add trend charts for overall populations 

- django_project/fixtures/population_status.json
> remove partial open from population status fixture

- django_project/frontend/api_views/metrics.py
- django_project/frontend/tests/test_population_count_per_province.py
- django_project/frontend/utils/metrics.py
> fix queryset for total count per province

- django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
- django_project/frontend/src/services/api.ts
- django_project/species/test_species_models.py
- django_project/species/views.py
> modify Taxon List API based on current tab

- django_project/frontend/src/containers/OnlineFormPage/Forms/EventDetailForm.tsx
- django_project/frontend/src/models/Upload.ts
> change permit number to non numeric field

- django_project/frontend/api_views/population.py
- django_project/frontend/src/components/PropertySummaryTable/index.tsx
- django_project/frontend/src/containers/MainPage/Property/PropertyInfo.tsx
- django_project/frontend/src/containers/OnlineFormPage/Forms/SpeciesDetail.tsx
- django_project/frontend/tests/test_population.py
- django_project/species/scripts/data_upload.py
- django_project/species/test_api_views.py
> Fix area field as integer value
