kartoza/sawps

django_project/frontend/api_views/population.py

This is for #675. Added filter by taxon_rank = 'species' for pulling species list for dropdown values.

Filter taxon with rank species only

---

django_project/frontend/api_views/population.py
django_project/frontend/src/containers/MainPage/Upload/index.scss
django_project/occurrence/serializers.py

This is to fix empty list in sample unit dropdown. Related issue: #676.
Also, fix button Online Form on hover:
cc: @amyburness

Fix sample unit serializer online form

---

django_project/plumber_initialize.py

Removing django_setup since it is not needed and causing permission issue during plumber initialization.

Remove django setup from plumber init script

---

django_project/frontend/views/base_view.py

key error was a result of users who dont have an organisation or not having an organisation under selection thus the request object did not have the key error . to resolve the issue I have observed it is not neccessary to filter notifications by organisation as the notifcations are filtered by user and users without organisation can still get notifications for the reminders they set for themselves.

patch: resolve key error

---

django_project/frontend/views/base_view.py

patch to resolve TypeError: int() argument must be a string, a bytes-like object or a real number, not 'SimpleLazyObject'

patch: use user id instead

---

django_project/frontend/api_views/statistical.py

check if row.count_method is not None. If it's not None, access its name

patch: prevent noneType object has not attribute 'name'

---

django_project/frontend/tests/test_2fa_view.py
django_project/frontend/views/totp_device.py

This is the error that is being triggered by using the simplaLazy object

patch: use id instead to prevent simpleLazy object error

---

django_project/frontend/src/components/LandingPage/LandingPagePopulationOverview/OverviewCardsHolder/index.tsx
django_project/frontend/src/components/LandingPage/LandingPagePopulationOverview/SpeciesChart/styles.scss

This is to fix #887. Charts will be grouped by 6, 3, 2, and 1.
Preview:

fix responsiveness charts on landing page

---

django_project/frontend/utils/organisation.py
django_project/frontend/views/base_view.py
django_project/sawps/tests/test_activate_account.py
django_project/sawps/tests/test_user.py
django_project/sawps/views.py

Description:
when user is super user but doesn't have an organisation currently set on the current organisation field of the user profile this attrib error on the screenshot was arising,
when normal user who doesn't have a user profile logs in to the platform ,the user profile does not exist on user was occurring 
To resolve these , when a user activates their account after registration a user profile will be attached to them 
when a super user doesn't have a current organisation set the attrib error will be supressed

Tinashechiraya patch 4

---

django_project/frontend/views/users.py

Description 
an incorrect value was set on the number of rows per page this was causing only a single row to appear per page
@LunaAsefaw on the screenshot you provided https://github.com/kartoza/sawps/issues/969 if you notice there is a arrow icon indicating there is another page available if you clicked it then you were going to see the other organisational member ...but I have resolved that minor bug in this pr .
Also note if you're adding a member to an organisation from the admin side make sure you add them to the organisation users and organisation invites models with their joined status set to true ...this way they will appear on this page for whichever organisation you would have added them for.

patch: use correct value for rows per page #969

---

django_project/frontend/templates/organisations.html
django_project/frontend/templates/users.html

[Screencast from 21-09-2023 09:43:48.webm](https://github.com/kartoza/sawps/assets/70011086/648e29f8-252f-4a8b-8a38-ca1273af120b)
Description:
when the user role is not admin or organisation manager or super user the add user column will be removed and the data use permissions switches will be disabled and the update button unavailable

Enforce user roles on organisations pages

---

django_project/frontend/templates/allauth_2fa/backup_tokens.html
django_project/frontend/templates/notifications.html
django_project/frontend/templates/organisations.html
django_project/frontend/templates/profile.html
django_project/frontend/templates/reminders.html

Description:
the footer was in the wrong position on all profile pages so I have applied the min height for the page content so that the footer is positioned at the bottom of the page
I have added a overflow property so that on smaller devices the tables on reminders, notifications are scrollable

Make profile pages responsive

---

django_project/frontend/templates/organisations.html

[Screencast from 21-09-2023 21:53:48.webm](https://github.com/kartoza/sawps/assets/70011086/011c0a05-f229-4b73-89ff-d52e976b63a8)
Description:
I have made the word agreement clickable . The link to the agreement is still to be provided .
I have also added a patch to display a single organisation if there is only one

patch: adjustments to organisations page #1080

---

django_project/frontend/templates/organisations.html
django_project/frontend/templates/profile.html

Description: 
I have positioned the footer correctly on the profile page
[Screencast from 22-09-2023 09:42:37.webm](https://github.com/kartoza/sawps/assets/70011086/d341eced-b0ef-4fea-a32b-02a5925638dd)
I have prevented the data use permissions statement from changing
[Screencast from 22-09-2023 10:17:13.webm](https://github.com/kartoza/sawps/assets/70011086/6ee6e4dc-206a-4bd9-87fd-3145a4e84cc6)

patch: place footer at the bottom of the page on profile page

---

django_project/frontend/templates/profile.html
django_project/frontend/tests/base_view.py
django_project/frontend/tests/test_data_table.py
django_project/frontend/tests/test_map.py
django_project/frontend/tests/test_metrics.py
django_project/frontend/tests/test_notifications.py
django_project/frontend/tests/test_organisations.py
django_project/frontend/tests/test_property.py
django_project/frontend/tests/test_users_view.py
django_project/species/test_species_models.py
django_project/stakeholder/admin.py
django_project/stakeholder/models.py
django_project/stakeholder/test_profile.py
django_project/stakeholder/test_stakeholder_models.py
django_project/stakeholder/test_tasks.py
django_project/stakeholder/test_view.py

Needed for the future user role implementation.
Summary of the changes : 
- Moved the "UserProfile" admin section to be under "Django Users." This ensures that we don't have two separate "Users" sections in the admin
- UserProfiles are now automatically created when a User is created. This is achieved using post_save signals, as seen here:
https://github.com/kartoza/sawps/compare/main...dimasciput:sawps:user_profile_improvement?expand=1#diff-c2067d2b677df444591d90f9ddb2bc59d01a009ea635aff491cd8984a324d8b2R168
- Tests have been updated to accommodate these changes

User profile improvements

---

django_project/frontend/src/containers/MainPage/MainPage.tsx
django_project/frontend/tests/test_map_view.py
django_project/frontend/urls.py
django_project/frontend/views/map.py

[Screencast from 22-09-2023 13:30:24.webm](https://github.com/kartoza/sawps/assets/70011086/d39ed6c5-71a3-4f6a-b78e-8d850e1f4dbc)
Description:
Explore pages have been renamed
metrics to charts
data to report

Rename explore tabs

---

django_project/frontend/src/containers/MainPage/SideBar/index.scss

[Screencast from 23-09-2023 15:15:48.webm](https://github.com/kartoza/sawps/assets/70011086/7be5e6c5-772a-4294-be01-7c8503b6e593)
Description
I have removed the whitespace at the bottom of the sidebar...now the contents of the sidebar fit the entire height of the sidebar

patch: adjust sidebar contents to take full height

---

django_project/frontend/src/containers/OnlineFormPage/Forms/ConfidenceRating.tsx
django_project/frontend/src/containers/OnlineFormPage/Forms/SpeciesDetail.tsx
django_project/frontend/src/containers/OnlineFormPage/Forms/index.scss

[Screencast from 23-09-2023 20:49:12.webm](https://github.com/kartoza/sawps/assets/70011086/52b79178-fabb-4917-955e-42e31d2a36c9)
Description:
The population estimate certainty can now be entered using the confidence rating component which displays the confidence levels 
the user can either use the slider to select the confidence level or select a value
and as the user does the slider or the values will reflect those changes
choosing 1 will show text very unconfident whilst 10 will show very confident 
[Screencast from 23-09-2023 21:50:36.webm](https://github.com/kartoza/sawps/assets/70011086/bb7ee20d-6fbf-49f0-8db4-4308f2eeea78)
Description:
I have increased the length of the select boxes so that the dropdown icon doess not overlap text

Population estimate rating

---

django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx

This PR is for the issue #1129 
Before:- 
After:-

Remove population category from spatial filter

---

django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
django_project/frontend/src/containers/MainPage/SideBar/index.scss

Description:
I have added to the existing search results ,nomatim results this will help in searching by location
clicking on any location in the dropdown will navigate to that location on the map
the results from the map are filtered to return only addresses within south africa 
now the user can search by property name or location/address
I have also styled the search box to match the existing style applied on the sidebar panel (icon + heading + search box )
[Screencast from 29-09-2023 03:24:01.webm](https://github.com/kartoza/sawps/assets/70011086/3c6c202d-5b22-44cd-9c11-ed8aad5f1bd9)
due to some limitations on my localhost ,i use the compact dump file ,my map only shows a small portion and the areas dont have names thus I am unable to fully demostrate how the feature is working fully …

Struggling to find property

---

django_project/frontend/api_views/data_table.py
django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx

[Screencast from 29-09-2023 13:16:20.webm](https://github.com/kartoza/sawps/assets/70011086/ef658ed5-3a72-4054-8237-ff165f348ea7)
Description:
on the explore page in the sidebar panel filters section
a user can select a property and doing so will trigger a navigation to the properties location on the map
a user can select multiple properties and it will adjust the maps focus to the area that covers the properties selected
a user can select all properties and it will readjust the map accordingly 
deselecting all properties will restore the map to its intial state when the component is loaded 
the search box styling has been improved to match the styling of the other checkboxes on the page

feat: select property ,zoom on map #1128

---

django_project/frontend/src/containers/MainPage/Metrics/AgeGroupBarChart.tsx
django_project/frontend/src/containers/MainPage/Metrics/PropertyType.tsx

[Screencast from 09-10-2023 21:09:42.webm](https://github.com/kartoza/sawps/assets/70011086/e7e57aba-01c9-47e9-802c-9d2574edb284)
Description
if there are multiple properties with the same property type name , the total area values will be summed
the legend has been removed
the horizontal axis labels have been added to represent each bar with the summed up total area

patch: update chart functionality #1232

---

django_project/frontend/utils/upload_file.py

@amyburness @Jeremy-Prior  In the frontend, I have a logic that will exclude ParentFarm parcel from selection. I remember I discussed it with Jeremy, because the ParentFarm is actually broken down to smaller parcel in FarmPortion.
This PR will also exclude ParentFarm for searching parcel during: shapefile upload and digitise function.
Below is the issue that I encountered, I have these parcels from digitise function:
But, after clicking save boundary, property geometry is added with ParentFarm parcel too.
Let me know if this PR makes sense,

Remove parent farm from search parcel

---

django_project/frontend/api_views/metrics.py
django_project/frontend/serializers/metrics.py
django_project/frontend/src/containers/MainPage/Metrics/ActivityCountAsPercentage.tsx
django_project/frontend/src/containers/MainPage/Metrics/DensityBarChart.tsx
django_project/frontend/src/containers/MainPage/Metrics/PopulationCategoryChart.tsx
django_project/frontend/src/containers/MainPage/Metrics/PopulationEstimateCategory.tsx
django_project/frontend/src/containers/MainPage/Metrics/PopulationEstimateCategoryAsPercentage.tsx
django_project/frontend/src/containers/MainPage/Metrics/SpeciesCountAsPercentage.tsx
django_project/frontend/src/containers/MainPage/Metrics/SpeciesCountPerProvinceChart.tsx
django_project/frontend/src/containers/MainPage/Metrics/TotalCountPerActivity.tsx
django_project/frontend/src/containers/MainPage/Metrics/index.tsx
django_project/frontend/tests/test_metrics.py
django_project/frontend/tests/test_population_estimate_category.py
django_project/frontend/urls.py

[Screencast from 14-10-2023 17:07:41.webm](https://github.com/kartoza/sawps/assets/70011086/be8f1b42-fbd5-4919-86e7-92edb375faf4)
Description:
I have added 
Activity count as % of total population chart
total count per population estimate category chart
population estimate category count as % of the total population
I have arranged the ordering of category labels on population category chart
I have ordered the years from highest to lowest in the legend labels
I have adjust the size of the donut charts to be smaller so they can match the size of other charts
I will add the images to each donut chart on the responsiveness ticket #1231 as I'm still testing the responsiveness of the chart sizes

Add donut charts

---

django_project/frontend/src/containers/MainPage/Metrics/ActivityCountAsPercentage.tsx
django_project/frontend/src/containers/MainPage/Metrics/AreaAvailableLineChart.tsx
django_project/frontend/src/containers/MainPage/Metrics/DensityBarChart.tsx
django_project/frontend/src/containers/MainPage/Metrics/PopulationCategoryChart.tsx
django_project/frontend/src/containers/MainPage/Metrics/PopulationEstimateCategory.tsx
django_project/frontend/src/containers/MainPage/Metrics/PopulationEstimateCategoryAsPercentage.tsx
django_project/frontend/src/containers/MainPage/Metrics/PropertyAvailable.tsx
django_project/frontend/src/containers/MainPage/Metrics/PropertyType.tsx
django_project/frontend/src/containers/MainPage/Metrics/SpeciesCountAsPercentage.tsx
django_project/frontend/src/containers/MainPage/Metrics/TotalCountPerActivity.tsx
django_project/frontend/src/containers/MainPage/Metrics/index.tsx

[Screencast from 17-10-2023 03:10:42.webm](https://github.com/kartoza/sawps/assets/70011086/d7d3b397-f380-46af-9746-a2684a45e664)
Description:
I have set a maximum height on the donut chart grids ,this should prevent them from being too large 
I have added a background image to each donut chart with the appropriate dimensions
All the donut charts are responsive to the end year filter as they fetch data per year
If a chart has empty data it will not be rendered. Only charts with data will be shown 
when a property is selected charts that do not require specie selection will be rendered
when a specie is selected the charts with available data for the specific filter selections will be shown

Charts responsiveness

---

django_project/frontend/src/containers/MainPage/Metrics/DensityBarChart.tsx
django_project/frontend/src/containers/MainPage/Metrics/PopulationCategoryChart.tsx
django_project/frontend/src/containers/MainPage/Metrics/PropertyAvailable.tsx
django_project/frontend/src/containers/MainPage/Metrics/SpeciesCountPerProvinceChart.tsx

[Screencast from 18-10-2023 20:23:31.webm](https://github.com/kartoza/sawps/assets/70011086/d74db9f2-4ded-4595-b5b4-e5571401d32d)
Description:
I have changed the order of the bars and years on the charts that show years:
population category chart
density chart
total area available to species
total count of species per province
I have also fixed the total count of species per province showing empty chart when no data is available , now it won't be rendered

Change the order of all the charts bars

---

django_project/frontend/src/containers/MainPage/Metrics/ActivityCountAsPercentage.tsx
django_project/frontend/src/containers/MainPage/Metrics/PopulationEstimateCategory.tsx
django_project/frontend/src/containers/MainPage/Metrics/PopulationEstimateCategoryAsPercentage.tsx
django_project/frontend/src/containers/MainPage/Metrics/SpeciesCountAsPercentage.tsx
django_project/frontend/src/containers/MainPage/Metrics/TotalCountPerActivity.tsx
django_project/frontend/src/containers/MainPage/Metrics/index.tsx

I have slightly increased the size of the donut charts 
correctly positioned the image on the center of the donut 
and for legend labels with text thats too long it will trim the label and add '...' showing the label goes on

Adjust donut charts

---

django_project/frontend/templates/about.html
django_project/frontend/templates/allauth_2fa/authenticate.html

Before:-
After:-
Space between the second paragraph and the link

Fix UI authentication page

---

django_project/frontend/src/containers/MainPage/Trends/index.scss
django_project/frontend/src/containers/MainPage/Trends/index.tsx

The same className from trends component is overwriting the size of trend charts in landing page.
Before:
After fix:

Fix styling frontend page trend charts

---

django_project/frontend/src/containers/MainPage/Data/Topper.tsx
django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
django_project/frontend/src/reducers/SpeciesFilter.ts

This is PR for #1342 #1433 
I tested by updating some organisations and properties into having comma. Now the count between filters and topper are equal.

feature/1342-1433: Fix Organisation, Property, and Activity count discrepancy

---

django_project/frontend/api_views/map.py
django_project/frontend/tests/test_map.py

This is to fix superuser not able to see the property information when clicking on properties in the map.

Fix find property by coordinate for superuser

---

django_project/frontend/src/containers/MainPage/Map/MapUtility.ts

Before:
After:
When zoom in:
cc: @Jeremy-Prior

Show properties label on top of dot point

---

django_project/frontend/utils/map.py

This is to fix legends for properties choropleth layer that does not start with 0 when there is property without any data. Discussion for this issue is from [this comment](https://github.com/kartoza/sawps/pull/1519#issuecomment-1794465210).
cc: @LunaAsefaw

Fix min count for properties population layer

---

django_project/frontend/src/components/LandingPage/LandingPagePopulationOverview/SpeciesChart/index.tsx

This is for #1413. Fix color for x/y axis and legend.
Preview:

fix color for trend chart in landing page

---

django_project/frontend/src/containers/MainPage/Map/MapUtility.ts

This is to fix properties points layer is not visible (see Luna's comment in [here](https://github.com/kartoza/sawps/issues/812#issuecomment-1804682010)
Now we can see the dot points of property:

fix properties point layer visibility

---

django_project/frontend/src/containers/MainPage/Data/Topper.tsx
django_project/frontend/src/containers/MainPage/Metrics/index.tsx

This is PR for #1589 
I remove Population Estimate Category As Percentage as per discussion with @LunaAsefaw . I also changed Charts topper to only show single year, instead of year range.

feature/1589: Remove Population Estimate Category Percentage chart

---

django_project/frontend/src/containers/MainPage/index.scss

Preview for each tab:
- Map
- Reports
- Charts

fix main content height - map becomes hidden

---

django_project/frontend/src/containers/MainPage/Map/MapUtility.ts

This is to add border color to properties dot point so it will be much visible.
Preview:

add circle stroke for properties points

---

django_project/frontend/src/containers/MainPage/Property/PropertyInfo.tsx
django_project/frontend/src/containers/MainPage/Upload/SpeciesUploader.tsx
django_project/frontend/src/containers/MainPage/Upload/index.tsx
django_project/population_data/models.py
django_project/species/tasks/upload_species.py
django_project/species/test_api_views.py

This is for #1504 - fix dropzone is disabled after upload is error.
Preview:
Also made improvements:
- Add property short code to dropdown in Data Upload
- Add copy to clipboard for property code in info section
- Reset canceled field when task is being rerun

Fix upload popup error

---

django_project/frontend/api_views/metrics.py
django_project/frontend/src/containers/MainPage/Metrics/PropertyCountPerCategory.tsx
django_project/frontend/tests/test_metrics.py

fix/1621: Fix Chart UI

---

django_project/frontend/serializers/report.py
django_project/frontend/src/containers/MainPage/Data/index.tsx
django_project/frontend/tests/test_online_form_view.py
django_project/frontend/tests/test_serializers.py
django_project/frontend/utils/data_table.py
django_project/frontend/views/online_form.py

This is for #1717.
The edit icon is now hidden when user is not the owner. cc: @LunaAsefaw 
Preview:
This is also for #1727 - applies to online form only. (I will submit another PR for edit from csv/excel upload)

hide edit action when user is not the data owner

---

django_project/frontend/api_views/statistical.py
django_project/frontend/src/containers/MainPage/Trends/PropertyTrendSection.tsx
django_project/frontend/src/containers/MainPage/Trends/index.scss
django_project/frontend/tests/test_api_statistical.py

This is for #1667.
- Section title 'Property' if single property is displayed
- Section title 'Properties' if multiple properties are displayed
- Remove section if there is no property is selected
- Fix API error when no property is selected

Fix api error when property id is empty

---

django_project/frontend/src/containers/MainPage/Metrics/index.tsx

feature/1741: Remove SpeciesCountAsPercentage from chart page

---

django_project/frontend/src/containers/MainPage/Data/index.tsx

This is PR for #1745, #1748, #1749
After some digging, they are related. After updating the code to not send property parameter when user role is Data Consumer, the aggregation works correctly (Data Consumer also cannot filter by property).

Data Consumer Reports Aggregation Issue

---

django_project/frontend/src/containers/MainPage/Metrics/AreaAvailableLineChart.tsx

This is PR for #1761 
When there is only 1 data, render empty chart to make it consistent with other charts.
[Kazam_screencast_00063.webm](https://github.com/kartoza/sawps/assets/7352963/3dc4980c-6070-4cb5-946b-9f65a7b25433)

fix/1761: Area Comparison Chart Issue

---

django_project/frontend/src/components/PdfReport/PopulationCategoryChart.tsx
django_project/frontend/src/containers/MainPage/MainPage.tsx
django_project/frontend/src/containers/MainPage/SideBar/Filter.tsx
django_project/frontend/src/containers/MainPage/Trends/NationalTrendSection.tsx
django_project/frontend/src/reducers/SpeciesFilter.ts

reset start year filter when navigate from reports tab

---

django_project/frontend/utils/metrics.py

Issue: When there is a population data in a year having two activities data, the count in the province becomes double with all selected activities in the filter.
To fix this issue, I apply distinct to the sum aggregate function so it won't sum the same population record twice.

add distinct for sum population data

---

django_project/frontend/src/components/LandingPage/LandingPagePopulationOverview/SpeciesChart/index.tsx
django_project/frontend/src/containers/MainPage/Trends/PopulationTrendChart.tsx

This is for #1670.
Changes:
- Starts y axis at zero (no need to do this from R code)
- Set rotation to x labels to 45 degrees
Previews:

Fix trends chart x and y labels

---

django_project/frontend/templates/base.html

This is for #1883.
Preview:
@dimasciput, this is a workaround because there should be a message from allauth changed password view. But, we only display message with tag 'notification' only. Do you know why we do that? 
Perhaps, the better approach is to override allauth change password view (like logout view in PR #1909) and send message with notification tag.

show message password changed from allauth view

---

django_project/frontend/api_views/population.py
django_project/frontend/serializers/report.py
django_project/frontend/src/containers/OnlineFormPage/Forms/FormWizard.tsx
django_project/frontend/src/containers/OnlineFormPage/Forms/SpeciesDetail.tsx
django_project/frontend/src/models/Upload.ts
django_project/frontend/tests/test_population.py
django_project/frontend/urls.py
django_project/population_data/models.py
django_project/population_data/tests/test_population_data_models.py
django_project/species/scripts/data_upload.py

This is for #1946.
Preview:
Logic:
- When adding new data, check and show confirmation if there is existing data for that year
- When editing existing data and change the year, check and show confirmation if there is existing data for that year

Feat enable edit year

---

django_project/property/tasks/check_overlaps.py
django_project/property/tests/test_check_overlaps.py

This is for #1922. Ignore overlaps with area less than or equal to 1 sqm

exclude overlaps less than or equal to 1sqm

---

django_project/frontend/api_views/map.py
django_project/frontend/src/models/ContextLayer.ts
django_project/frontend/src/reducers/LayerFilter.ts
django_project/frontend/tests/test_map.py

This is for #2022.
Preview:
Also add cache-control header to the NGI layer API.

Hide other layer when NGI layer is selected

---

django_project/frontend/templates/organisations.html

This is for #2021.
Preview:
Other tab:

fix style for organisation page title

---

deployment/docker/requirements.txt

This is to fix below error:
```
File "/home/web/django_project/frontend/utils/data_table.py", line 9, in <module>
import pandas as pd
File "/usr/local/lib/python3.10/site-packages/pandas/__init__.py", line 46, in <module>
from pandas.core.api import (
File "/usr/local/lib/python3.10/site-packages/pandas/core/api.py", line 1, in <module>
from pandas._libs import (
File "/usr/local/lib/python3.10/site-packages/pandas/_libs/__init__.py", line 18, in <module>
from pandas._libs.interval import Interval
File "interval.pyx", line 1, in init pandas._libs.interval
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

fix numpy dependency error
